server:
  port: 8080
# 此处存放系统级别，git存放应用级别
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.kobe.pojo
myname: zhangsan teach in class1904xxx666777888899999
